workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: 15.1   # 👈 CLAVE

    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Update CocoaPods
        script: |
          pod repo update

      - name: Build iOS (simulator)
        script: flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app